[package]
name = "reponere"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_yml = "0.0.12"
serde_json = "1.0.149"
regex = "1.12.2"
version-compare = "0.2.1"
tempfile = "3.24.0"
thiserror = "2.0.18"
git2 = "0.20.3"
